---
title: "EML assembly workflow for NES-LTER underway chlorophyll data"
author: "Joe Futrelle"
date: "February 2022"
output: html_notebook
---


```{r}
library(dplyr)
library(readr)
library(here)
library(glue)
library(readxl)
library(xml2)
library(rlog)
library(ggplot2)

library(EML)
library(EMLassemblyline)
library(ediutilities)
```

[something about the package itself here]

Data is provided in a git submodule. When cloning this repository, use this
command or equivalent, replacing ... with this repository's URL:

git clone --recurse-submodules ...

Data assembly:

```{r}
# location of submodule containing data tables
data_dir <- here('nes-lter-chla-post-calibration')

# assemble union table for post-cal fluorometer data
post_cal_fluo <- merge_csv_directory(glue('{data_dir}/post-cal-fluo'))

# remove columns that will not be published
post_cal_fluo$fluorescence_manufacturer_cal <- NULL

# round post-calibrated fluorometer values to two digits past the decimal
post_cal_fluo$fluorescence_post_cal <- round(post_cal_fluo$fluorescence_post_cal, digits=2)

# assemble union table for discrete data
uw_discrete_cont_match <- merge_csv_directory(glue('{data_dir}/uw_discrete_cont_match'))

# remove columns that will not be published
uw_discrete_cont_match$fluo1_wetstar_match <- NULL
uw_discrete_cont_match$fluo2_ecofl_match <- NULL

# make the quality flag a factor
uw_discrete_cont_match$iode_quality_flag <- as.factor(uw_discrete_cont_match$iode_quality_flag)
post_cal_fluo$iode_quality_flag <- as.factor(post_cal_fluo$iode_quality_flag)

# create an output directory for the merged, adjusted data tables
output_dir <- here('data_tables')
dir.create(output_dir)

# write data to be published to CSV files used in the EML assembly workflow
write_csv(post_cal_fluo, glue('{output_dir}/chl-transect-underway-post-cal.csv'), na='NaN')
write_csv(uw_discrete_cont_match, glue('{output_dir}/chl-transect-underway-discrete.csv'), na='NaN')
```
```{r}
# show summary statistics for data tables

summary(uw_discrete_cont_match)
```
```{r}
summary(post_cal_fluo)
```

Plot discrete locations on a map

```{r}
map_locs(uw_discrete_cont_match, region="transect")
```
```{r}
# plot the data distributions by quality flag

p <- ggplot(post_cal_fluo, aes(x=as.factor(iode_quality_flag), y=fluorescence_post_cal)) + 
   geom_boxplot() + xlab('iode_quality_flag')
p
```
```{r}
p <- ggplot(uw_discrete_cont_match, aes(x=as.factor(iode_quality_flag), y=chl)) + 
   geom_boxplot() + xlab('iode_quality_flag')
p
```

Assemble EML metadata templates based on the provided Excel template

```{r}
# define input files
edi_filename <- "chl-transect-underway"
metadata <- glue('{edi_filename}-info')
pkg_id <- "knb-lter-nes.12.2"

# Make EML Templates 
excel_to_template(metadata_path = metadata, 
                  edi_filename = edi_filename, 
                  rights = "CCBY")

sheet_to_tsv('chl-transect-underway-info.xlsx', 'CategoricalVariables',
             glue::glue('catvars_chl-transect-underway-post-cal.txt'))

sheet_to_tsv('chl-transect-underway-info.xlsx', 'CategoricalVariables',
             glue::glue('catvars_chl-transect-underway-discrete.txt'))

sheet_to_tsv('chl-transect-underway-post-cal.xlsx', 'ColumnHeaders',
             glue::glue('attributes_chl-transect-underway-post-cal.txt'))

sheet_to_tsv('chl-transect-underway-discrete.xlsx', 'ColumnHeaders',
             glue::glue('attributes_chl-transect-underway-discrete.txt'))

EMLassemblyline::template_core_metadata(path=here(), license='CCBY')
```
Compute spatiotemporal coverage and generate EML

```{r}

temp_coverage <- temporal_coverage(append(post_cal_fluo$date_time_utc,
                                          uw_discrete_cont_match$date_time_utc))

dataset_title = 'Underway discrete chlorophyll and post-calibrated underway fluorometer data during NES-LTER Transect cruises, ongoing since 2019'

make_eml(path=here(),
         data.path=output_dir,
         dataset.title=dataset_title,
         data.table=c('chl-transect-underway-discrete.csv',
                      'chl-transect-underway-post-cal.csv'),
         data.table.description=c('Underway discrete chlorophyll data during NES-LTER Transect cruises',
                                  'Post-calibrated underway fluorometer data during NES-LTER Transect cruises'),
         data.table.name = c('NES-LTER underway discrete chlorophyll data',
                             'NES-LTER post-calibrated underway fluorometer data'),
         temporal.coverage = temp_coverage,
         geographic.description = "NES-LTER Transect",
         geographic.coordinates =
           geographic_coordinates(append(post_cal_fluo$latitude,
                                         uw_discrete_cont_match$latitude),
                                  append(post_cal_fluo$longitude,
                                         uw_discrete_cont_match$longitude)),
         maintenance.description = "ongoing",
         user.id = "NES",
         user.domain = "LTER",
         package.id = pkg_id)

# insert parent project node
project_insert(pkg_id)
```

